name: cbase
version: 0.0.0
homepage: https://github.com/morloc-lib/cbase
synopsis: Core types and functions for C
description: This is totally experimental
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-lib/cbase
bug-reports: https://github.com/morloc-lib/cbase
